/* Automatically generated by po2tbl.sed from gxmlviewer.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"XML Viewer", 2},
  {"Select File", 3},
  {"xmlviewer for gnome.", 4},
  {"About", 5},
  {"\
gXmlViewer\n\
Author : Sean Stuckless", 6},
  {"Ok", 7},
  {"Couldn't find pixmap file: %s", 8},
  {"Couldn't create pixmap from file: %s", 9},
  {"Error loading pixmap file: %s", 10},
};

int _msg_tbl_length = 10;
