/* Automatically generated by po2tbl.sed from gxmlviewer.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"XML Viewer", 2},
  {"Select File", 3},
  {"xmlviewer for gnome.", 4},
  {"Couldn't find pixmap file: %s", 5},
  {"Couldn't create pixmap from file: %s", 6},
};

int _msg_tbl_length = 6;
