/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
#include <gtk/gtk.h>

GtkWidget* create_mainWin (void);
GtkWidget* create_fileselection (void);
GtkWidget* create_aboutBox (void);
GtkWidget *xmlwindow_new(GtkWidget *parent);
