/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gnome.h>

#include "interface.h"
#include "support.h"
#include "xmlparser.h"
#include "constants.h"
#include "gxmlviewer.h"

/* this is required so that we can always access the window */
GtkWidget *gMainWindow;

int
main (int argc, char *argv[])
{
  GtkWidget *mainWin;
  char *filename = argv[1];

#ifdef ENABLE_NLS
  bindtextdomain (PACKAGE, PACKAGE_LOCALE_DIR);
  textdomain (PACKAGE);
#endif

  gnome_init ("gxmlviewer", VERSION, argc, argv);

  /* create the main display */
  mainWin = create_mainWin ();
  gtk_window_set_title(GTK_WINDOW(mainWin), GXMLVIEWER_TITLE);
  gMainWindow = mainWin;

  /* check for swallowed parameter. if it exists then remove the menu */
  if (argc > 1 && strcmp(argv[1],"swallowed") == 0) {
	  GtkWidget *menu = lookup_widget(mainWin, MENU_CONTAINER);
	  gtk_widget_hide(menu);
	  filename = argv[2];
  }

  /* show the xml file */
  if (filename != NULL && show_xmlfile(filename, lookup_widget(mainWin, XMLTREE_WIDGET_NAME))) {
     /* there were errors */
  }
 
  /* show the main window */ 
  gtk_widget_show (mainWin);

  /* gtk main event loop handler */
  gtk_main ();
  return 0;
}

